x <- ymd_hms("2009-08-03 12:01:59.23")
round_date(x, ".5s")
round_date(x, "sec")
round_date(x, "second")
round_date(x, "minute")
round_date(x, "5 mins")
round_date(x, "hour")
round_date(x, "2 hours")
round_date(x, "day")
round_date(x, "week")
round_date(x, "month")
round_date(x, "bimonth")
round_date(x, "quarter") == round_date(x, "3 months")
round_date(x, "halfyear")
round_date(x, "year")
x <- ymd("2000-01-01")
ceiling_date(x, "month")
browser()
ceiling_date(x, "month", change_on_boundary = TRUE)
return(TRUE)


library(profvis)
library(bench)
profvis::profvis({
    x <- integer()
    for (i in 1:1e4) {
        x <- c(x, i)
    }
})
